// frontend/src/components/AdminPanel.jsx
import { useCallback, useEffect, useState } from "react";
import { apiFetch, readJson } from "../lib/api.js";

export function AdminPanel({ open, onClose }) {
  const [users, setUsers] = useState([]);
  const [stats, setStats] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    const [u, s] = await Promise.all([apiFetch("/api/admin/users"), apiFetch("/api/admin/stats")]);
    const uj = await readJson(u);
    const sj = await readJson(s);
    if (!u.ok) setError("Impossibile caricare utenti");
    else setUsers(uj.users || []);
    if (s.ok) setStats(sj);
    setLoading(false);
  }, []);

  useEffect(() => {
    if (open) load();
  }, [open, load]);

  const updateQuota = async (id, standard_monthly, hires_monthly) => {
    const res = await apiFetch(`/api/admin/users/${id}/quota`, {
      method: "PUT",
      body: JSON.stringify({ standard_monthly, hires_monthly }),
    });
    if (res.ok) load();
  };

  const resetMonth = async (id) => {
    const res = await apiFetch(`/api/admin/users/${id}/reset`, { method: "POST" });
    if (res.ok) load();
  };

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-40 flex items-start justify-center overflow-y-auto bg-black/70 p-4">
      <div className="mt-8 w-full max-w-5xl rounded-2xl border border-laba-border bg-laba-bg p-6 shadow-2xl">
        <div className="mb-4 flex items-center justify-between">
          <h2 className="font-display text-xl font-bold">Admin</h2>
          <button type="button" onClick={onClose} className="text-sm text-zinc-400 hover:text-white">
            Chiudi
          </button>
        </div>
        {stats && (
          <div className="mb-4 grid gap-2 text-xs text-zinc-400 sm:grid-cols-3">
            <div className="rounded-lg border border-laba-border bg-laba-surface px-3 py-2">
              Utenti: <strong className="text-white">{stats.totalUsers}</strong>
            </div>
            <div className="rounded-lg border border-laba-border bg-laba-surface px-3 py-2">
              Standard (mese): <strong className="text-white">{stats.standardUsedSum}</strong>
            </div>
            <div className="rounded-lg border border-laba-border bg-laba-surface px-3 py-2">
              Hi‑res (mese): <strong className="text-white">{stats.hiresUsedSum}</strong>
            </div>
          </div>
        )}
        {loading && <p className="text-sm text-zinc-500">Caricamento…</p>}
        {error && <p className="text-sm text-red-400">{error}</p>}
        <div className="overflow-x-auto">
          <table className="w-full min-w-[640px] text-left text-xs">
            <thead>
              <tr className="border-b border-laba-border text-zinc-500">
                <th className="py-2 pr-2">Email</th>
                <th className="py-2 pr-2">Ruolo</th>
                <th className="py-2 pr-2">Standard</th>
                <th className="py-2 pr-2">Hi‑res</th>
                <th className="py-2">Azioni</th>
              </tr>
            </thead>
            <tbody>
              {users.map((u) => (
                <tr key={u.id} className="border-b border-laba-border/60">
                  <td className="py-2 pr-2 text-zinc-200">{u.email}</td>
                  <td className="py-2 pr-2">{u.role}</td>
                  <td className="py-2 pr-2">
                    {u.standard_used ?? 0} / {u.standard_monthly ?? "—"}
                  </td>
                  <td className="py-2 pr-2">
                    {u.hires_used ?? 0} / {u.hires_monthly ?? "—"}
                  </td>
                  <td className="py-2">
                    <button
                      type="button"
                      className="mr-2 text-laba-accent hover:underline"
                      onClick={() => {
                        const sm = window.prompt("Standard mensile", String(u.standard_monthly ?? 200));
                        const hm = window.prompt("Hi‑res mensile", String(u.hires_monthly ?? 20));
                        if (sm != null && hm != null) updateQuota(u.id, Number(sm), Number(hm));
                      }}
                    >
                      Quota
                    </button>
                    <button
                      type="button"
                      className="text-zinc-400 hover:underline"
                      onClick={() => resetMonth(u.id)}
                    >
                      Reset mese
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

// frontend/src/components/AdminPanel.vue
<script setup>
import { ref, watch } from "vue"
import { apiFetch, readJson } from "../lib/api.js"

const props = defineProps({
  open: Boolean,
})

const emit = defineEmits(["close"])

const users = ref([])
const stats = ref(null)
const loading = ref(false)
const error = ref(null)

async function load() {
  loading.value = true
  error.value = null
  const [u, s] = await Promise.all([apiFetch("/api/admin/users"), apiFetch("/api/admin/stats")])
  const uj = await readJson(u)
  const sj = await readJson(s)
  if (!u.ok) error.value = "Impossibile caricare utenti"
  else users.value = uj.users || []
  if (s.ok) stats.value = sj
  loading.value = false
}

watch(() => props.open, (val) => {
  if (val) load()
})

async function updateQuota(id, standard_monthly, hires_monthly) {
  const res = await apiFetch(`/api/admin/users/${id}/quota`, {
    method: "PUT",
    body: JSON.stringify({ standard_monthly, hires_monthly }),
  })
  if (res.ok) load()
}

async function resetMonth(id) {
  const res = await apiFetch(`/api/admin/users/${id}/reset`, { method: "POST" })
  if (res.ok) load()
}

function promptQuota(u) {
  const sm = window.prompt("Standard mensile", String(u.standard_monthly ?? 200))
  const hm = window.prompt("Hi‑res mensile", String(u.hires_monthly ?? 20))
  if (sm != null && hm != null) updateQuota(u.id, Number(sm), Number(hm))
}
</script>

<template>
  <div
    v-if="open"
    class="fixed inset-0 z-40 flex items-start justify-center overflow-y-auto bg-black/70 p-4"
  >
    <div class="mt-8 w-full max-w-5xl rounded-2xl border border-laba-border bg-laba-bg p-6 shadow-2xl">
      <div class="mb-4 flex items-center justify-between">
        <h2 class="font-display text-xl font-bold">Admin</h2>
        <button type="button" @click="emit('close')" class="text-sm text-zinc-400 hover:text-white">
          Chiudi
        </button>
      </div>

      <div v-if="stats" class="mb-4 grid gap-2 text-xs text-zinc-400 sm:grid-cols-3">
        <div class="rounded-lg border border-laba-border bg-laba-surface px-3 py-2">
          Utenti: <strong class="text-white">{{ stats.totalUsers }}</strong>
        </div>
        <div class="rounded-lg border border-laba-border bg-laba-surface px-3 py-2">
          Standard (mese): <strong class="text-white">{{ stats.standardUsedSum }}</strong>
        </div>
        <div class="rounded-lg border border-laba-border bg-laba-surface px-3 py-2">
          Hi‑res (mese): <strong class="text-white">{{ stats.hiresUsedSum }}</strong>
        </div>
      </div>

      <p v-if="loading" class="text-sm text-zinc-500">Caricamento…</p>
      <p v-if="error" class="text-sm text-red-400">{{ error }}</p>

      <div class="overflow-x-auto">
        <table class="w-full min-w-[640px] text-left text-xs">
          <thead>
            <tr class="border-b border-laba-border text-zinc-500">
              <th class="py-2 pr-2">Email</th>
              <th class="py-2 pr-2">Ruolo</th>
              <th class="py-2 pr-2">Standard</th>
              <th class="py-2 pr-2">Hi‑res</th>
              <th class="py-2">Azioni</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="u in users" :key="u.id" class="border-b border-laba-border/60">
              <td class="py-2 pr-2 text-zinc-200">{{ u.email }}</td>
              <td class="py-2 pr-2">{{ u.role }}</td>
              <td class="py-2 pr-2">
                {{ u.standard_used ?? 0 }} / {{ u.standard_monthly ?? "—" }}
              </td>
              <td class="py-2 pr-2">
                {{ u.hires_used ?? 0 }} / {{ u.hires_monthly ?? "—" }}
              </td>
              <td class="py-2">
                <button
                  type="button"
                  class="mr-2 text-laba-accent hover:underline"
                  @click="promptQuota(u)"
                >
                  Quota
                </button>
                <button
                  type="button"
                  class="text-zinc-400 hover:underline"
                  @click="resetMonth(u.id)"
                >
                  Reset mese
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>
